### ISSUE TITLE
Using umlauts

### ISSUE THREAD

**Issue by flosse** [mikedilger/email-format#18]
How can I create an eMail with umlauts?
Using them causes `InvalidInput, error: Trailing input at byte` :(

**Comment by mikedilger** [comment]
Internet mail was originally limited to 7-bit ASCII.  MIME added support for the use of 8-bit character sets in body parts.

This crate handles the lower 7-bit ASCII layer.  You can compose a MIME message with another crate such as https://github.com/mikedilger/mime-multipart and use that as the body (and some of the headers).

**Comment by mikedilger** [comment]
I've updated the README to show how you can use MIME with this crate.

**Comment by mikedilger** [comment]
Bah, it's not working.  `mime_multipart` needs work.

edited: Or something else.  I may support content-transfer-encoding and encode the body thusly, e.g. quoted-printable or base64.

**Comment by flosse** [comment]
Tanks!
In the meantime I just created my mail manually using `format!` and the `quoted_printable` crate ;-)

**Comment by mikedilger** [comment]
Sweet.  #19 tracks this issue now for this crate.  I do plan to supply something better eventually.
