### ISSUE TITLE
Support for custom headers?

### ISSUE THREAD

**Issue by darnir** [mikedilger/email-format#23]
I'd like to use this crate in my application and am missing one crucial feature. I want to add custom headers to the email struct I create and then save it to disk.

I did not see anything in the documentation that allows custom / arbitrary email headers to be added to the email. Could you please implement this feature?

**Comment by mikedilger** [comment]
Search the docs for `OptionalField`

This crate is still missing a lot of email headers that were defined outside of RFC5322, but luckily custom fields were in that standard.
